"""Added on cascade delete, now possible. Fixed tipization

Revision ID: 153f5a98e475
Revises: a8f083c1e155
Create Date: 2026-04-03 17:57:54.574667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '153f5a98e475'
down_revision: Union[str, Sequence[str], None] = 'a8f083c1e155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('check_results_endpoint_id_fkey'), 'check_results', type_='foreignkey')
    op.create_foreign_key(None, 'check_results', 'endpoints', ['endpoint_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('endpoints_site_id_fkey'), 'endpoints', type_='foreignkey')
    op.create_foreign_key(None, 'endpoints', 'sites', ['site_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'endpoints', type_='foreignkey')
    op.create_foreign_key(op.f('endpoints_site_id_fkey'), 'endpoints', 'sites', ['site_id'], ['id'])
    op.drop_constraint(None, 'check_results', type_='foreignkey')
    op.create_foreign_key(op.f('check_results_endpoint_id_fkey'), 'check_results', 'endpoints', ['endpoint_id'], ['id'])
    # ### end Alembic commands ###
