"""actual init of db model

Revision ID: 5e2bd4afb761
Revises: 83d37ce6ad71
Create Date: 2026-03-26 01:10:58.710292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e2bd4afb761'
down_revision: Union[str, Sequence[str], None] = '83d37ce6ad71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sites', ['base_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sites', type_='unique')
    # ### end Alembic commands ###
