"""empty message

Revision ID: 71ea240ac269
Revises: b533a3a291b9
Create Date: 2026-03-24 21:19:30.059733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ea240ac269'
down_revision: Union[str, Sequence[str], None] = 'b533a3a291b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('check_results_endpoint_id_fkey'), 'check_results', type_='foreignkey')
    op.create_foreign_key(None, 'check_results', 'endpoints', ['endpoint_id'], ['id'])
    op.alter_column('endpoints', 'sampling_interval',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('endpoints_site_id_fkey'), 'endpoints', type_='foreignkey')
    op.create_foreign_key(None, 'endpoints', 'sites', ['site_id'], ['id'])
    op.drop_constraint(op.f('sites_base_url_key'), 'sites', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('sites_base_url_key'), 'sites', ['base_url'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'endpoints', type_='foreignkey')
    op.create_foreign_key(op.f('endpoints_site_id_fkey'), 'endpoints', 'sites', ['site_id'], ['id'], ondelete='CASCADE')
    op.alter_column('endpoints', 'sampling_interval',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'check_results', type_='foreignkey')
    op.create_foreign_key(op.f('check_results_endpoint_id_fkey'), 'check_results', 'endpoints', ['endpoint_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
