"""empty message

Revision ID: 83d37ce6ad71
Revises: 71ea240ac269
Create Date: 2026-03-24 22:42:40.175673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d37ce6ad71'
down_revision: Union[str, Sequence[str], None] = '71ea240ac269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('site_path_uc', 'endpoints', ['site_id', 'path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('site_path_uc', 'endpoints', type_='unique')
    # ### end Alembic commands ###
