"""Added method, timeout to endpoint model and is_avaible to checkresult model

Revision ID: a8f083c1e155
Revises: 5e2bd4afb761
Create Date: 2026-04-01 23:42:39.582811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f083c1e155'
down_revision: Union[str, Sequence[str], None] = '5e2bd4afb761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_results', sa.Column('is_available', sa.Boolean(), nullable=False))
    op.add_column('endpoints', sa.Column('method', sa.String(), nullable=False))
    op.add_column('endpoints', sa.Column('timeout', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoints', 'timeout')
    op.drop_column('endpoints', 'method')
    op.drop_column('check_results', 'is_available')
    # ### end Alembic commands ###
